### PR TITLE
Add support for IPMI address pools

### LINKED ISSUE #6: Add new /api/ipmi/pools endpoint
The ipmi pools endpoint has been added to collins. This is a ticket to keep track of adding that functionality to this client.

### PR DESCRIPTION
**Pull request by defect**
This adds support for the new IPMI address pools features. There are two parts to it:

First, I'm adding `IpmiPool` as an optional part of the `AssetCreateOpts` struct, which will tell the API which IPMI address pool to use when creating an asset.

Second, in order to support `GET /api/ipmi/pools` I'm piggy-backing on the IPAM code since it's very similar. I'm breaking out the code from `IPAMService.Pools()` so that both it and the new `IPAMService.IpmiPools()` can share it.

Closes #6.

@tumblr/collins @michaeljs1990 @byxorna

### CODE REVIEW

**Comment by defect** [comment]
Actually, maybe this should live in it's own `IpmiService` to match better with the API and the ruby client. Thoughts?

**Comment by michaeljs1990** [comment]
Nice, thanks for adding this! I think it makes sense to keep it consistent with the ruby client. Although it seems a tad silly right now with only one ipmi endpoint i figured if any additional endpoints were added in the future it was best they didn't get hidden all over the place inside other apis.

**Comment by defect** [comment]
Yup, i agree. I moved it to it's own `IPMIService` thing.

**Comment by michaeljs1990** [comment]
👍 ✅  <- I can't actually accept but these emoji's seem just as valuable.

**Comment by byxorna** [comment]
@defect this LGTM! i cannot accept/land either (can i be added as contributor for this project as well ;D)

:white_check_mark:

**Comment by roymarantz** [comment]
👍

**Pull request merged**
